### ISSUE TITLE
Emoji's  aren't rendering at all

### ISSUE THREAD

**Issue by Z3R0-cmd** [2b2t-Utilities/emoji-api#3]
When I use your prebuilt .jar file (Release 1.0) nothing is displaying in chat. I've tried saying ":8ball:" and quite a few other emoji's that are in the folder. I think i must be doing something wrong but im not sure what

**Comment by Z3R0-cmd** [comment]
Also the mod does not show up in the "mods" gui

**Comment by Tigermouthbear** [comment]
this is an api and does not run as a forge mod. You should use https://github.com/2b2t-Utilities/2b2t-Utilities
